In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
import pandas as pd

fake_df = pd.read_csv("../Data/Fake.csv")
true_df = pd.read_csv("../Data/True.csv")

print("Fake News Dataset:")
display(fake_df.head())

print("True News Dataset:")
display(true_df.head())

Fake News Dataset:

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

True News Dataset:

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [3]:
print("Fake News Shape:", fake_df.shape)
print("True News Shape:", true_df.shape)

print("\nColumns:")
print(fake_df.columns)

print("\nMissing Values in Fake Dataset:")
print(fake_df.isnull().sum())

print("\nMissing Values in True Dataset:")
print(true_df.isnull().sum())

Fake News Shape: (23481, 4)
True News Shape: (21417, 4)

Columns:
Index(['title', 'text', 'subject', 'date'], dtype='str')

Missing Values in Fake Dataset:
title      0
text       0
subject    0
date       0
dtype: int64

Missing Values in True Dataset:
title      0
text       0
subject    0
date       0
dtype: int64

In [4]:

fake_df["label"] = 0
true_df["label"] = 1

news_df = pd.concat([fake_df, true_df], ignore_index=True)

news_df = news_df.sample(frac=1, random_state=42).reset_index(drop=True)

print("Combined Dataset Shape:", news_df.shape)

display(news_df.head())

Combined Dataset Shape: (44898, 5)

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [8]:
print(news_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 1.7 MB
None

In [7]:
news_df.describe(include="all")

,title,text,subject,date,label
count,44898,44898,44898,44898,44898.000000
unique,38729,38646,8,2397,NaN
top,Factbox: Trump fills top jobs for his administ...,,politicsNews,"December 20, 2017",NaN
freq,14,627,11272,182,NaN
mean,NaN,NaN,NaN,NaN,0.477015
std,NaN,NaN,NaN,NaN,0.499477
min,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,NaN,0.000000
75%,NaN,NaN,NaN,NaN,1.000000
max,NaN,NaN,NaN,NaN,1.000000

In [10]:
print(news_df["label"].value_counts())

label
0    23481
1    21417
Name: count, dtype: int64

In [11]:
X = news_df["text"]

y = news_df["label"]

print("Feature Shape:", X.shape)
print("Label Shape:", y.shape)

print("\nFirst News Article:\n")
print(X.iloc[0][:500])   # First 500 characters

print("\nLabel:", y.iloc[0])

Feature Shape: (44898,)
Label Shape: (44898,)

First News Article:

21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein

Label: 0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data :", X_test.shape)

Training Data: (35918,)
Testing Data : (8980,)

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

print("Training Matrix Shape:", X_train.shape)
print("Testing Matrix Shape :", X_test.shape)

Training Matrix Shape: (35918, 111193)
Testing Matrix Shape : (8980, 111193)

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

print("✅ Model trained successfully!")

✅ Model trained successfully!

In [16]:
y_pred = model.predict(X_test)

print("First 10 Predictions:")
print(y_pred[:10])

First 10 Predictions:
[0 1 1 0 1 1 0 0 1 0]

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.982739420935412

Confusion Matrix:
[[4618   92]
 [  63 4207]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      4710
           1       0.98      0.99      0.98      4270

    accuracy                           0.98      8980
   macro avg       0.98      0.98      0.98      8980
weighted avg       0.98      0.98      0.98      8980

In [18]:
import joblib

# Save the trained Logistic Regression model
joblib.dump(model, "../Models/logistic_regression_model.pkl")

print("✅ Logistic Regression model saved successfully!")

✅ Logistic Regression model saved successfully!

In [19]:
import joblib

joblib.dump(vectorizer, "../Models/tfidf_vectorizer.pkl")

print("✅ TF-IDF Vectorizer saved successfully!")

✅ TF-IDF Vectorizer saved successfully!